script.Parent.Scanner.Transparency=.9
wait()
script.Parent.Scanner.Transparency=.8
wait()
script.Parent.Scanner.Transparency=.7
wait()
script.Parent.Scanner.Transparency=.6
wait()
script.Parent.Scanner.Transparency=.5
wait()
script.Parent.Scanner.Transparency=.4
wait()
script.Parent.Scanner.Transparency=.3
wait()
script.Parent.Scanner.Transparency=.2
wait()
script.Parent.Scanner.Transparency=.1
wait()
script.Parent.Scanner.Transparency=0
wait(1)
script.Parent.T2.Disabled=false
wait(2.5)
script.Parent.T1.Disabled=false
script.Parent.T2.Disabled=true
wait(2.5)
script.Parent.T1.Disabled=true
script.Parent.Scanner.Transparency=.1
wait()
script.Parent.Scanner.Transparency=.2
wait()
script.Parent.Scanner.Transparency=.3
wait()
script.Parent.Scanner.Transparency=.4
wait()
script.Parent.Scanner.Transparency=.5
wait()
script.Parent.Scanner.Transparency=.6
wait()
script.Parent.Scanner.Transparency=.7
wait()
script.Parent.Scanner.Transparency=.8
wait()
script.Parent.Scanner.Transparency=.9
wait()
script.Parent.Scanner.Transparency=1
script.Disabled=true